create table orders
(id bigint generated by default as identity,
 amount numeric not null,
 address varchar(255) not null,
 delivery_date date not null,
 primary key (id));

 create table products
 (id bigint generated by default as identity,
  inventory int not null,
  amount numeric not null,
  name varchar(255) not null,
  primary key (id));

 create table order_details
 (id bigint generated by default as identity,
   order_id bigint not null references orders(id),
   product_id bigint not null references products(id),
   quantity int not null,
   primary key (id));
